#!/bin/sh

docker build -t rate-limiter:0.0.1  -f ./rate-limit/Dockerfile . \
&& docker build  -t target-client:0.0.1 -f ./target-client/Dockerfile . \
&& docker build -t target-service:0.0.1 -f ./target-service/Dockerfile . \
&& docker compose build \
&& docker compose up