version: "3"

services:
  rate-limiter:
    ports:
      - "8080:8080"

    image: rate-limiter:0.0.1

  target-client:
    stdin_open: true
    tty: true
    image: target-client:0.0.1
    environment:
      STORAGE_CLIENT_BASE_PATH: http://storage:8080

  target-service:
    ports:
      - "8081:8081"

    image: target-service:0.0.1



