version: "3"

services:
  storage:
    ports:
      - "8080:8080"

    image:
      storage-service:0.0.1

  client:
    stdin_open: true
    tty: true
    image: client:0.0.1
    environment:
      STORAGE_CLIENT_BASE_PATH: http://storage:8080


