version: "3"

services:
  storage:
    ports:
      - "8000:8000"

    image:
      storage-service:0.0.1

    command: java -jar ./server-component-0.0.1-SNAPSHOT.jar

  client:
    stdin_open: true
    tty: true
    image: client:0.0.1
    environment:
      STORAGE_CLIENT_BASE_PATH: http://storage:8080


