limit:
  descriptors:
    - key: UserIP
      value: "127.0.0.1"
      unit: Hour
      requests_per_unit: 3

    - key: EndpointUrl
      value: "/griddy/devious"
      unit: Hour
      requests_per_unit: 1