descriptors:
  - key: userIP
    unit: Second
    requests_per_unit: 20

  - key: userIP
    value: "127.0.0.1"
    unit: Minute
    requests_per_unit: 100

  - key: endpointUrl
    value: "/griddy/devious"
    unit: Minute
    requests_per_unit: 10