spring:
  quartz:
    job-store-type: memory

storage:
  component:
    jobs:
      merge-ss-table:
        cron: 0/2 * * * * ?  # every 2 seconds

    filesystem:
      storage-path: ${STORAGE_PATH:data}
      type: lsm
    compression:
      allocatedBufferSize: 4096
      type: deflate
    flush:
      tableParentDir: "PLACEHOLDER"
      keyValueDelimiter: ":"
      blockSizeInBytes: 65536
      entryDelimiter: ";"
      readBufferSize: 4096
    memtable:
      maxSize: 20
