storage:
  component:
    filesystem:
      storage-path: ${STORAGE_PATH:data}
      type: lsm
    compression:
      allocatedBufferSize: 4096
      type: deflate
    flush:
      tableParentDir: "D:\\labs\\5sem\\labs_highload\\itmo-is-25-highload\\db"
      keyValueDelimiter: ":"
      blockSizeInBytes: 65536
      entryDelimiter: ";"
      readBufferSize: 4096
    memtable:
      maxSize: 20

