spring:
  quartz:
    job-store-type: memory


storage:
  component:
    redis:
      host: localhost
      port: 6380
      username: redis
      password: kek123
    jobs:
      merge-ss-table:
        cron: 0/2 * * * * ?  # every 2 seconds

    redis-cluster:
      nodes:
        -
          host: localhost
          port: 7000
          username: redis
          password: bazinga
        -
          host: localhost
          port: 7001
          username: redis
          password: bazinga
        -
          host: localhost
          port: 7002
          username: redis
          password: bazinga

        -
          host: localhost
          port: 7003
          username: redis
          password: bazinga

        -
          host: localhost
          port: 7004
          username: redis
          password: bazinga

        -
          host: localhost
          port: 7005
          username: redis
          password: bazinga

    filesystem:
      storage-path: ${STORAGE_PATH:data}
      type: redis-cluster
    compression:
      allocatedBufferSize: 4096
      type: deflate
    flush:
      tableParentDir: /Users/mindtable/ITMO/5-sem/itmo-is25-highload/testRes
      keyValueDelimiter: ":"
      blockSizeInBytes: 65536
      entryDelimiter: ";"
      readBufferSize: 4096
    memtable:
      maxSize: 30
debug: true

logging:
  level:
    io.lettuce.*: trace
